site_name: My Awesome Book
nav:
  - ПРОЛОГ: chapters/0_prolog.md
  - Глава 1. Путь Тима на север: chapters/chapter1.md
  - Глава 10. Танец огня и железа: chapters/chapter10.md
  - Часть 2. СЕВЕР: chapters/chapter11.md
  - Глава 12. Перекрёсток: chapters/chapter12.md
  - chapter13: chapters/chapter13.md
  - Глава 2. Искра: chapters/chapter2.md
  - Глава 3. Медведь: chapters/chapter3.0.md
  - Глава 4 — Далёкие горизонты: chapters/chapter3.1.md
  - Глава 5. Горная деревня: chapters/chapter4.0.md
  - Глава 6 Кузница: chapters/chapter4.1.md
  - Глава 7. Ритмы горной деревни: chapters/chapter5.md
  - Глава 8. Предчувствие бури: chapters/chapter6.md
  - Глава 9. Урок для варваров: chapters/chapter7.md
  - z_plot: chapters/z_plot.md

theme:
  name: readthedocs
